---

- include: pkg-install.yml package=bzip2
- include: pkg-install.yml package=less
- include: pkg-install.yml package=lsb-release
- include: pkg-install.yml package=net-tools
- include: pkg-install.yml package=ntp
- include: pkg-install.yml package=openssh-server

- name: Install openssh-server ssh_config
  template: src=etc/ssh/ssh_config.j2 dest=/etc/ssh/ssh_config owner=root group=root mode=0644
  become: yes

- name: Install openssh-server sshd_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  become: yes

# TODO Enable this when enabling AuthorizedKeysFile in sshd_config
#- name: Create /etc/ssh/authorized_keys directory
#  file: path=/etc/ssh/authorized_keys state=directory owner=root group=root mode=0700
#  become: yes

# TODO Restart ssh service after the changes above? (Not every time - only if changes were made)

- include: pkg-install.yml package=python
- include: pkg-install.yml package=sshfs
- include: pkg-install.yml package=sudo
- include: pkg-install.yml package=unzip
- include: pkg-install.yml package=vim

