---

#---
# Install miscellaneous standard packages
#---

# Per https://askubuntu.com/questions/297560/ntpd-vs-ntpdate-pros-and-cons
# ntpdate (for occasional use via cron) is deprecated; only use ntpd from the
# ntp package now.
# (7/26/2020) Newer versions of Raspberry Pi OS and other Debian distros might
# also be coming out with systemd-timesyncd as a client-only solution for NTP.
# Let's start leaving ntp out of Raspberry Pi installations for now.
- include: pkg-install.yml package=ntp

#---
# Install SSH server
#---

- include: pkg-install.yml package=openssh-server

- name: Install openssh-server ssh_config
  template: src=etc/ssh/ssh_config.j2 dest=/etc/ssh/ssh_config owner=root group=root mode=0644
  become: yes

- name: Install openssh-server sshd_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  become: yes

# TODO Enable this when enabling AuthorizedKeysFile in sshd_config
#- name: Create /etc/ssh/authorized_keys directory
#  file: path=/etc/ssh/authorized_keys state=directory owner=root group=root mode=0700
#  become: yes

# TODO Restart ssh service after the changes above? (Not every time - only if changes were made)

- include: pkg-install.yml package=sshfs


#---
# Finishing up
#---

- name: Ensure services are running
  service:
     name: "{{ item }}"
     state: started
     enabled: yes
  with_items:
     - ntp
     - ssh
  
