---

# List received from tasksel:
#
#    # tasksel --list-tasks
#    # tasksel --task-packages gnome-desktop

# TODO turn this on later--it works fine, but it takes a long time to install; might be preferable to modify README.md to check this box during the initial install since the packages will be available locally on the install CD
# TODO On the other hand leave this on now; the README.md in dev-inf specifies to check Desktop Environment, so the desktop environment will already be installed from local media if desired/appropriate; and then this will update any applicable packages since the ones on the CD will be old. Need to capture this in the comments here and then remove these TODOs.
- include: ../../common/tasks/pkg-install.yml package=task-gnome-desktop

