---

- name: Install inittab - this is for disabling Ctrl+Alt+Del (TODO in GUI - except it's probably not just for workstations)
  template: src=etc/inittab.j2 dest=/etc/inittab owner=root group=root mode=0644
  become: yes

