---

#---
# Install Postfix to send outgoing mail
#---

# Note: Debian Stretch appears to have a problem installing postfix only--mail
# was not being sent with the following messages in /var/log/mail:
#
#     Jul  4 23:01:23 hostname postfix/qmgr[11815]: XXXXXXXXXX: from=<user@host>, size=384, nrcpt=1 (queue active)
#     Jul  4 23:01:25 hostname postfix/smtp[11964]: warning: SASL authentication failure: No worthy mechs found
#     Jul  4 23:01:25 hostname postfix/smtp[11964]: XXXXXXXXXX: ... status=deferred (SASL authentication failed; cannot authenticate to server ...: no mechanism available)
#
# Installing libsasl2-modules manually helped get past this.

- include: common-inf/roles/common-packages/tasks/pkg-install.yml package=mailutils
- include: common-inf/roles/common-packages/tasks/pkg-install.yml package=postfix
- include: common-inf/roles/common-packages/tasks/pkg-install.yml package=libsasl2-modules

- name: Install postfix/sasl_passwd
  template: src=etc/postfix/sasl_passwd.j2 dest=/etc/postfix/sasl_passwd owner=root group=root mode=0600
  notify:
     - Update Postfix sasl_passwd lookup table
  become: yes

- name: Install postfix/generic
  template: src=etc/postfix/generic.j2 dest=/etc/postfix/generic owner=root group=root mode=0644
  notify:
     - Update Postfix generic lookup table
  become: yes

- name: Install postfix/main.cf
  template: src=etc/postfix/main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644
  notify:
     - Restart postfix
  become: yes

- name: Install /etc/issue
  blockinfile:
    path: /etc/issue
    block: |
       :
       : * eth0: \4{eth0}
       : * wlan0: \4{wlan0}
       :
    marker: "+--- {mark} IP Addresses ---"
    marker_begin: Here is the list of
    marker_end: Completed listing
  become: yes
  tags: debug

- name: Install /etc/rc.local
  template: src=etc/rc.local.j2 dest=/etc/rc.local owner=root group=root mode=0755
  become: yes
