---

#---
# Install SSH server
#---

- include: common-inf/roles/common-packages/tasks/pkg-install.yml package=openssh-server

- name: Install openssh-server sshd_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
     - Ensure ssh server restarted
  become: yes

# TODO Enable this when enabling AuthorizedKeysFile in sshd_config
#- name: Create /etc/ssh/authorized_keys directory
#  file: path=/etc/ssh/authorized_keys state=directory owner=root group=root mode=0700
#  become: yes

