---

# TODO split from common: move to dedicated initial package installation role?
- name: Run apt-get update
  apt:
     update_cache: yes
  become: yes

- include: pkg-install.yml package=bzip2
- include: pkg-install.yml package=less
- include: pkg-install.yml package=lsb-release
- include: pkg-install.yml package=net-tools
- include: pkg-install.yml package=ntp
- include: pkg-install.yml package=openssh-server

- name: Install openssh-server ssh_config
  template: src=etc/ssh/ssh_config.j2 dest=/etc/ssh/ssh_config owner=root group=root mode=0644
  become: yes

- name: Install openssh-server sshd_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  become: yes

- include: pkg-install.yml package=python
- include: pkg-install.yml package=sshfs
- include: pkg-install.yml package=sudo
- include: pkg-install.yml package=unzip
- include: pkg-install.yml package=vim

# TODO split from common: move to workstations or basic-workstations role? -- this is for disabling Ctrl+Alt+Del in GUI - except it's probably not just for workstations
- name: Install inittab
  template: src=etc/inittab.j2 dest=/etc/inittab owner=root group=root mode=0644
  become: yes

# TODO split from common: move to dedicated adduser setup role?
- name: Install adduser.conf
  template: src=etc/adduser.conf.j2 dest=/etc/adduser.conf owner=root group=root mode=0644
  become: yes

- include: setup-skel.yml dest=/etc/skel
- include: setup-skel.yml dest=/root

# Add users after setting up /etc/skel and /etc/adduser.conf above
- name: Add user accounts
  include: create-user.yml
  with_dict: "{{ users }}"

