---

- include: setup-apt-sources-list.yml component=main
- include: setup-apt-sources-list.yml component=non-free
- include: setup-apt-sources-list.yml component=contrib

- name: Verify cdrom line disabled in /etc/apt/sources.list
  command: /bin/grep -q '^[^#].*cdrom' /etc/apt/sources.list
  register: command_result
  failed_when: command_result.rc == 0

- name: Run apt-get update
  apt:
     update_cache: yes
  become: yes

