---
# Setup apt sources.list and run apt-get update

# Do not run these on Raspbian (arm), but we do want `apt-get update` below.

- include: setup-apt-sources-list.yml component=main
  when: ansible_architecture == "x86_64"

- include: setup-apt-sources-list.yml component=non-free
  when: ansible_architecture == "x86_64"

- include: setup-apt-sources-list.yml component=contrib
  when: ansible_architecture == "x86_64"


- name: Verify cdrom line disabled in /etc/apt/sources.list
  command: /bin/grep -q '^[^#].*cdrom' /etc/apt/sources.list
  register: command_result
  failed_when: command_result.rc == 0

# TODO Add these?
#- name: Install gnupg-agent (unmet dependency in Buster?)
#  include: common-inf/roles/common-packages/tasks/pkg-install.yml package=gnupg-agent
#
#- name: Install gnupg (unmet dependency in Buster?)
#  include: common-inf/roles/common-packages/tasks/pkg-install.yml package=gnupg

- name: Run apt-get update
  apt:
     update_cache: yes
  become: yes

